config/routes.rb
Rails.application.routes.draw do
  
  resources :notes

  get "contract_services/addContract"
  get "contract_services/modifyContract"
  get "contract_services/sendForOptimize"
  get "contract_services/approveContract"
  get "contract_services/rejectContract"
  get "contract_services/getAllContracts"
  post 'contract/create_tier'
  get 'contract/create_tier'
   get 'contract/newFromScratch'
  post 'contract/newFromScratch'

AdInServices::Application.routes.draw do
  

  resources :notes

  namespace :api do
  get 'price_rules_services/addPriceRule'
  end

  namespace :api do
  get 'price_rules_services/updatePriceRule'
  end

  namespace :api do
  get 'price_rules_services/removePriceRule'
  end

  namespace :api do
  get 'price_rules_services/getAllPriceRulesForCategory'
  end

  namespace :api do
  get 'price_rules_services/getAllPriceRuleForProductIdAndLocationId'
  end

  namespace :api do
  get 'price_rules_services/getAllPriceRulesForCategoriesAndAttributes'
  end

  namespace :api do
  get 'price_rules_services/getAllPriceRulesForLocationsAndAttributes'
  end

  namespace :api do
  get 'price_grids_services/addPriceGrid'
  end

  namespace :api do
  get 'price_grids_services/updatePriceGrid'
  end

  namespace :api do
  get 'price_grids_services/removePriceGrid'
  end

  namespace :api do
  get 'price_grids_services/getPriceGridByCategories'
  end

  namespace :api do
  get 'price_grids_services/getPriceGridByLocation'
  end

  namespace :api do
  get 'price_grids_services/getPriceGridByCategoryAndLocation'
  end

  namespace :api do
  get 'price_grids_services/getPriceGridByProductIdAndLocationId'
  end

  resources :price_grids

  resources :price_rules

  resources :product_attributes

  resources :custom_attributes
  
  get 'custom_attributes/index'
  post 'custom_attributes/add'
  get 'custom_attributes/new'
  
  namespace :api do
  get 'product_services/getAllDepartments'
  end

  namespace :api do
  get 'product_services/getCategoriesByDepartment'
  end

  namespace :api do
  get 'product_services/getSubCategoriesForCategory'
  end

  namespace :api do
  get 'product_services/getSegmentsForSubCategory'
  end

  namespace :api do
  get 'product_services/getProductsByDepartment'
  end

  namespace :api do
  post 'product_services/getProductsByCategory'
  end

  namespace :api do
  get 'product_services/getProductsBySubCategory'
  end

  namespace :api do
  get 'product_services/getProductsBySegment'
  end
  
  namespace :api do
  get 'product_services/getProductsByCustomAttributes'
 
  end
  
  namespace :api do
  get 'product_services/getAllattributes'
  end

  namespace :api do
  get 'ad_in_services_controller/getDepartments'
  
  get '/getDepartments' => 'ad_in_services_controller#getDepartments' 
  
  get 'ad_in_services_controller/getCategoriesByDepartment'
  end

  


 resources :event_managements
  
end
end

app/models/note.rb
class Note < ActiveRecord::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render action: 'show', status: :created, location: @note }
      else
        format.html { render action: 'new' }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:user_id, :contract_id, :description)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :contract_id %><br>
    <%= f.number_field :contract_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h1>Listing notes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Contract</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.user_id %></td>
        <td><%= note.contract_id %></td>
        <td><%= note.description %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @note.user_id %>
</p>

<p>
  <strong>Contract:</strong>
  <%= @note.contract_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @note.description %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>