config/routes.rb
Rails.application.routes.draw do
  
  resources :notes

  get "contract_services/addContract"
  get "contract_services/modifyContract"
  get "contract_services/sendForOptimize"
  get "contract_services/approveContract"
  get "contract_services/rejectContract"
  get "contract_services/getAllContracts"
  post 'contract/create_tier'
  get 'contract/create_tier'
   get 'contract/newFromScratch'
  post 'contract/newFromScratch'

AdInServices::Application.routes.draw do
  

  resources :notes

  namespace :api do
  get 'price_rules_services/addPriceRule'
  end

  namespace :api do
  get 'price_rules_services/updatePriceRule'
  end

  namespace :api do
  get 'price_rules_services/removePriceRule'
  end

  namespace :api do
  get 'price_rules_services/getAllPriceRulesForCategory'
  end

  namespace :api do
  get 'price_rules_services/getAllPriceRuleForProductIdAndLocationId'
  end

  namespace :api do
  get 'price_rules_services/getAllPriceRulesForCategoriesAndAttributes'
  end

  namespace :api do
  get 'price_rules_services/getAllPriceRulesForLocationsAndAttributes'
  end

  namespace :api do
  get 'price_grids_services/addPriceGrid'
  end

  namespace :api do
  get 'price_grids_services/updatePriceGrid'
  end

  namespace :api do
  get 'price_grids_services/removePriceGrid'
  end

  namespace :api do
  get 'price_grids_services/getPriceGridByCategories'
  end

  namespace :api do
  get 'price_grids_services/getPriceGridByLocation'
  end

  namespace :api do
  get 'price_grids_services/getPriceGridByCategoryAndLocation'
  end

  namespace :api do
  get 'price_grids_services/getPriceGridByProductIdAndLocationId'
  end

  resources :price_grids

  resources :price_rules

  resources :product_attributes

  resources :custom_attributes
  
  get 'custom_attributes/index'
  post 'custom_attributes/add'
  get 'custom_attributes/new'
  
  namespace :api do
  get 'product_services/getAllDepartments'
  end

  namespace :api do
  get 'product_services/getCategoriesByDepartment'
  end

  namespace :api do
  get 'product_services/getSubCategoriesForCategory'
  end

  namespace :api do
  get 'product_services/getSegmentsForSubCategory'
  end

  namespace :api do
  get 'product_services/getProductsByDepartment'
  end

  namespace :api do
  post 'product_services/getProductsByCategory'
  end

  namespace :api do
  get 'product_services/getProductsBySubCategory'
  end

  namespace :api do
  get 'product_services/getProductsBySegment'
  end
  
  namespace :api do
  get 'product_services/getProductsByCustomAttributes'
 
  end
  
  namespace :api do
  get 'product_services/getAllattributes'
  end

  namespace :api do
  get 'ad_in_services_controller/getDepartments'
  
  get '/getDepartments' => 'ad_in_services_controller#getDepartments' 
  
  get 'ad_in_services_controller/getCategoriesByDepartment'
  end

  


 resources :event_managements
  
end
end

app/models/concerns/price_grid.rb
class PriceGrid < ActiveRecord::Base
end

app/models/price_grid.rb
class PriceGrid < ActiveRecord::Base
end

app/controllers/price_grids_controller.rb
class PriceGridsController < ApplicationController
  before_action :set_price_grid, only: [:show, :edit, :update, :destroy]

  # GET /price_grids
  # GET /price_grids.json
  def index
    @price_grids = PriceGrid.all
    logger.info { "finally in the logger" }
    
  end

  # GET /price_grids/1
  # GET /price_grids/1.json
  def show
  end

  # GET /price_grids/new
  def new
    @price_grid = PriceGrid.new
  end

  # GET /price_grids/1/edit
  def edit
  end

  # POST /price_grids
  # POST /price_grids.json
  def create
    @price_grid = PriceGrid.new(price_grid_params)

    respond_to do |format|
      if @price_grid.save
        format.html { redirect_to @price_grid, notice: 'Price grid was successfully created.' }
        format.json { render :show, status: :created, location: @price_grid }
      else
        format.html { render :new }
        format.json { render json: @price_grid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /price_grids/1
  # PATCH/PUT /price_grids/1.json
  def update
    respond_to do |format|
      if @price_grid.update(price_grid_params)
        format.html { redirect_to @price_grid, notice: 'Price grid was successfully updated.' }
        format.json { render :show, status: :ok, location: @price_grid }
      else
        format.html { render :edit }
        format.json { render json: @price_grid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /price_grids/1
  # DELETE /price_grids/1.json
  def destroy
    @price_grid.destroy
    respond_to do |format|
      format.html { redirect_to price_grids_url, notice: 'Price grid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price_grid
      @price_grid = PriceGrid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def price_grid_params
      params.require(:price_grid).permit(:name, :description, :price_vehicle_id, :price_rule_id, :from_price, :to_price, :price_candidates, :multiples, :created_by, :updated_by)
    end
end

app/helpers/price_grids_helper.rb
module PriceGridsHelper
end

app/views/price_grids/_form.html.erb
<%= form_for(@price_grid) do |f| %>
  <% if @price_grid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@price_grid.errors.count, "error") %> prohibited this price_grid from being saved:</h2>

      <ul>
      <% @price_grid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price_vehicle_id %><br>
    <%= f.number_field :price_vehicle_id %>
  </div>
  <div class="field">
    <%= f.label :price_rule_id %><br>
    <%= f.number_field :price_rule_id %>
  </div>
  <div class="field">
    <%= f.label :from_price %><br>
    <%= f.number_field :from_price %>
  </div>
  <div class="field">
    <%= f.label :to_price %><br>
    <%= f.number_field :to_price %>
  </div>
  <div class="field">
    <%= f.label :price_candidates %><br>
    <%= f.text_field :price_candidates %>
  </div>
  <div class="field">
    <%= f.label :multiples %><br>
    <%= f.text_field :multiples %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br>
    <%= f.text_field :created_by %>
  </div>
  <div class="field">
    <%= f.label :updated_by %><br>
    <%= f.text_field :updated_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/price_grids/edit.html.erb
<h1>Editing price_grid</h1>

<%= render 'form' %>

<%= link_to 'Show', @price_grid %> |
<%= link_to 'Back', price_grids_path %>

app/views/price_grids/index.html.erb
<h1>Listing price_grids</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price vehicle</th>
      <th>Price rule</th>
      <th>From price</th>
      <th>To price</th>
      <th>Price candidates</th>
      <th>Multiples</th>
      <th>Created by</th>
      <th>Updated by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @price_grids.each do |price_grid| %>
      <tr>
        <td><%= price_grid.name %></td>
        <td><%= price_grid.description %></td>
        <td><%= price_grid.price_vehicle_id %></td>
        <td><%= price_grid.price_rule_id %></td>
        <td><%= price_grid.from_price %></td>
        <td><%= price_grid.to_price %></td>
        <td><%= price_grid.price_candidates %></td>
        <td><%= price_grid.multiples %></td>
        <td><%= price_grid.created_by %></td>
        <td><%= price_grid.updated_by %></td>
        <td><%= link_to 'Show', price_grid %></td>
        <td><%= link_to 'Edit', edit_price_grid_path(price_grid) %></td>
        <td><%= link_to 'Destroy', price_grid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Price grid', new_price_grid_path %>

app/views/price_grids/new.html.erb
<h1>New price_grid</h1>

<%= render 'form' %>

<%= link_to 'Back', price_grids_path %>

app/views/price_grids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @price_grid.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @price_grid.description %>
</p>

<p>
  <strong>Price vehicle:</strong>
  <%= @price_grid.price_vehicle_id %>
</p>

<p>
  <strong>Price rule:</strong>
  <%= @price_grid.price_rule_id %>
</p>

<p>
  <strong>From price:</strong>
  <%= @price_grid.from_price %>
</p>

<p>
  <strong>To price:</strong>
  <%= @price_grid.to_price %>
</p>

<p>
  <strong>Price candidates:</strong>
  <%= @price_grid.price_candidates %>
</p>

<p>
  <strong>Multiples:</strong>
  <%= @price_grid.multiples %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @price_grid.created_by %>
</p>

<p>
  <strong>Updated by:</strong>
  <%= @price_grid.updated_by %>
</p>

<%= link_to 'Edit', edit_price_grid_path(@price_grid) %> |
<%= link_to 'Back', price_grids_path %>