config/routes.rb
Rails.application.routes.draw do
  
  resources :notes

  get "contract_services/addContract"
  get "contract_services/modifyContract"
  get "contract_services/sendForOptimize"
  get "contract_services/approveContract"
  get "contract_services/rejectContract"
  get "contract_services/getAllContracts"
  post 'contract/create_tier'
  get 'contract/create_tier'
   get 'contract/newFromScratch'
  post 'contract/newFromScratch'

AdInServices::Application.routes.draw do
  

  resources :notes

  namespace :api do
  get 'price_rules_services/addPriceRule'
  end

  namespace :api do
  get 'price_rules_services/updatePriceRule'
  end

  namespace :api do
  get 'price_rules_services/removePriceRule'
  end

  namespace :api do
  get 'price_rules_services/getAllPriceRulesForCategory'
  end

  namespace :api do
  get 'price_rules_services/getAllPriceRuleForProductIdAndLocationId'
  end

  namespace :api do
  get 'price_rules_services/getAllPriceRulesForCategoriesAndAttributes'
  end

  namespace :api do
  get 'price_rules_services/getAllPriceRulesForLocationsAndAttributes'
  end

  namespace :api do
  get 'price_grids_services/addPriceGrid'
  end

  namespace :api do
  get 'price_grids_services/updatePriceGrid'
  end

  namespace :api do
  get 'price_grids_services/removePriceGrid'
  end

  namespace :api do
  get 'price_grids_services/getPriceGridByCategories'
  end

  namespace :api do
  get 'price_grids_services/getPriceGridByLocation'
  end

  namespace :api do
  get 'price_grids_services/getPriceGridByCategoryAndLocation'
  end

  namespace :api do
  get 'price_grids_services/getPriceGridByProductIdAndLocationId'
  end

  resources :price_grids

  resources :price_rules

  resources :product_attributes

  resources :custom_attributes
  
  get 'custom_attributes/index'
  post 'custom_attributes/add'
  get 'custom_attributes/new'
  
  namespace :api do
  get 'product_services/getAllDepartments'
  end

  namespace :api do
  get 'product_services/getCategoriesByDepartment'
  end

  namespace :api do
  get 'product_services/getSubCategoriesForCategory'
  end

  namespace :api do
  get 'product_services/getSegmentsForSubCategory'
  end

  namespace :api do
  get 'product_services/getProductsByDepartment'
  end

  namespace :api do
  post 'product_services/getProductsByCategory'
  end

  namespace :api do
  get 'product_services/getProductsBySubCategory'
  end

  namespace :api do
  get 'product_services/getProductsBySegment'
  end
  
  namespace :api do
  get 'product_services/getProductsByCustomAttributes'
 
  end
  
  namespace :api do
  get 'product_services/getAllattributes'
  end

  namespace :api do
  get 'ad_in_services_controller/getDepartments'
  
  get '/getDepartments' => 'ad_in_services_controller#getDepartments' 
  
  get 'ad_in_services_controller/getCategoriesByDepartment'
  end

  


 resources :event_managements
  
end
end

app/models/custom_attribute.rb
class CustomAttribute < ActiveRecord::Base
  # include ActiveModel::Validations
  # validates_presence_of :name
  # validates_presence_of :value
  # validates_presence_of :description
  # validates_uniqueness_of :name
  # validates_with CustomValidator
  
  def self.getAllVersionableCustomAttributes
    @versionableCustomAttributes = CustomAttribute.where(versionable: "TRUE")
    return @versionableCustomAttributes
  end
  
end

app/controllers/custom_attributes_controller.rb
class CustomAttributesController < ApplicationController
 
  def index
    @custom_attributes= CustomAttribute.all
  end
 
  def new
    @custom_attributes = CustomAttribute.new

  end

  def add
    @custom_attributes = CustomAttribute.new(custom_attributes_params)

    if @custom_attributes.save
      render 'custom_attributes/add'
    else
      render 'new'
    end
  end

  def update
    @custom_attributes = CustomAttribute.find(params[:id])
    respond_to do |format|

      if @custom_attributes.update(custom_attribute_params)
        format.html { redirect_to(@custom_attributes, :notice => 'name was successfully updated.') }
        format.json { head :ok }
      else
        @custom_attributes= CustomAttribute.all.paginate(page: params[:page], per_page:5)
        format.html { render :action => "index" }
        format.json { respond_with_bip(@custom_attributes) }
      end
    end

  end

  def destroy
    @custom_attributes = CustomAttribute.find(params[:id])
    @custom_attributes.destroy
    respond_to do |format|
      format.html { redirect_to(@custom_attributes, :notice => 'name was successfully Deleted.') }
      format.json { head :no_content }
    end
  end


  private

  def set_custom_attributes
    @custom_attributes = CustomAttribute.find(params[:name])
  end

 
  def custom_attributes_params
    params.require(:custom_attributes).permit(:name,:description,:value,:attribute_type,:id)
  end

  def custom_attribute_params
    params.require(:custom_attribute).permit(:name,:description,:value,:attribute_type,:id)
  end
end

app/views/custom_attributes/_form.html.erb
<%= form_for :custom_attributes , url: { action: "add" } do |f| %>

<table class="table">
	<tr>
		<td><%= f.label :name %></td>
		<td><%= f.text_field :name ,:placeholder => "Enter Name"%></td>
	</tr>
	<tr>
		<td><%= f.label :attribute_type %></td>
		<td><%= f.radio_button :attribute_type, 'Number' ,:checked => true, :id => "attribute"   %>
		<%= f.label :attribute_type, "Number", :value => "Number"%>
		<%= f.radio_button :attribute_type, 'String', :checked => false,:id => "attribute"  %>
		<%= f.label :attribute_type, "String", :value => "String" %>
		<%= f.radio_button :attribute_type, 'NumberList', :checked => false,:id => "attribute"  %>
		<%= f.label :attribute_type, "NumberList", :value => "NumberList" %>
		<%= f.radio_button :attribute_type, 'StringList', :checked => false,:id => "attribute"%>
		<%= f.label :attribute_type, "StringList", :value => "StringList" %> </td>
	</tr>
	<tr>
		<td> <%= f.label :value %> </td>

		<td> <%= f.text_field :value, :id => "Value", :placeholder => "Enter Number" %> </td>

	</tr>

	<tr>
		<td> <%= f.label :description %> </td>
		<td> <%= f.text_area :description , :placeholder => "Add Description" %> </td>
	</tr>

</table>
<%= f.submit class:"btn btn-primary" %>
<% end %>

<script language="JavaScript">
	$(document).ready(function() {

		$(attribute).click(function() {
			var placeholder = "Enter " + this.value + "";
			$(Value).attr('placeholder', placeholder)

		});
	}); 
</script>

app/views/custom_attributes/_updateform.html.erb
<%= form_for :custom_attributes , url: { action: "update" } do |f| %>
<%= render "shared/error_messages", :target => @custom_attributes %>
<table class="table">
	<tr>
		<td><%= f.label :name %></td>
		<td><%= f.text_field :name ,:placeholder => "Enter Name"%></td>
	</tr>
	<tr>
		<td><%= f.label :attribute_type %></td>
		<td><%= f.radio_button :attribute_type, 'Number' ,:checked => true, :id => "attribute"   %>
		<%= f.label :attribute_type, "Number", :value => "Number"%>
		<%= f.radio_button :attribute_type, 'String', :checked => false,:id => "attribute"  %>
		<%= f.label :attribute_type, "String", :value => "String" %>
		<%= f.radio_button :attribute_type, 'NumberList', :checked => false,:id => "attribute"  %>
		<%= f.label :attribute_type, "NumberList", :value => "NumberList" %>
		<%= f.radio_button :attribute_type, 'StringList', :checked => false,:id => "attribute"%>
		<%= f.label :attribute_type, "StringList", :value => "StringList" %> </td>
	</tr>
	<tr>
		<td> <%= f.label :value %> </td>

		<td> <%= f.text_field :value, :id => "Value", :placeholder => "Enter Number" %> </td>

	</tr>

	<tr>
		<td> <%= f.label :description %> </td>
		<td> <%= f.text_area :description , :placeholder => "Add Description" %> </td>
	</tr>

</table>
<%= f.submit class:"btn btn-primary" %>
<% end %>

<script language="JavaScript">
	$(document).ready(function() {

		$(attribute).click(function() {
			var placeholder = "Enter " + this.value + "";
			$(Value).attr('placeholder', placeholder)

		});
	}); 
</script>


app/views/custom_attributes/add.html.erb
<div class="panel panel-primary">
	<div class="panel-body">
		<div class="container" >
			<div class="row">
				<div class="col-md-6">
					<%= render '/custom_attributes/form'%>
				</div>
			</div>
		</div>
	</div>
	<div class="panel-footer"></div>

app/views/custom_attributes/delete.html.erb
<h1>CustomAttributes#delete</h1>
<p>Find me in app/views/custom_attributes/delete.html.erb</p>

app/views/custom_attributes/index.html.erb
        <h3 class="list-group">Custom Attributes</h3>
		<table width="120px" id="example" >
			<thead>
				<div class="list-group">
					<tr>
						<th>Name</th>
						<th>Value</th>
						<th>Attribute Type</th>
						<th>Description</th>
				</div>
				</tr>
			</thead>

			<tbody>
				<% @custom_attributes.each do |custom_attribute| %>
				<% if custom_attribute%>
				<tr>
					<td><%= custom_attribute.name %></td>
					<td><%= custom_attribute.value %></td>
					<td><%= custom_attribute.attribute_type%></td>
					<td><%= custom_attribute.description %></td>
				</tr>
				<% end %>
				<% end %>
			</tbody>
		</table>
		
	<%= link_to 'New custom attribute', new_custom_attribute_path %>

app/views/custom_attributes/new.html.erb
<div class="panel panel-primary">
	<div class="panel-body">
		<div class="container" >
			<div class="row">
				<div class="col-md-6">
					<%= render '/custom_attributes/form'%>
				</div>
			</div>
		</div>
	</div>
	<div class="panel-footer"></div>

app/views/custom_attributes/update.html.erb
<div class="panel panel-primary">
	<div class="panel-heading">
		<h1 class="list-group">Update Attribute</h1>
	</div>
	<div class="panel-body">
		<div class="container" >
			<div class="row">
				<div class="col-md-6">
					<%= render '/custom_attributes/updateform'%>
				</div>
			</div>
		</div>
	</div>
	<div class="panel-footer"></div>