config/routes.rb
Rails.application.routes.draw do
  
  resources :notes

  get "contract_services/addContract"
  get "contract_services/modifyContract"
  get "contract_services/sendForOptimize"
  get "contract_services/approveContract"
  get "contract_services/rejectContract"
  get "contract_services/getAllContracts"
  post 'contract/create_tier'
  get 'contract/create_tier'
   get 'contract/newFromScratch'
  post 'contract/newFromScratch'

AdInServices::Application.routes.draw do
  

  resources :notes

  namespace :api do
  get 'price_rules_services/addPriceRule'
  end

  namespace :api do
  get 'price_rules_services/updatePriceRule'
  end

  namespace :api do
  get 'price_rules_services/removePriceRule'
  end

  namespace :api do
  get 'price_rules_services/getAllPriceRulesForCategory'
  end

  namespace :api do
  get 'price_rules_services/getAllPriceRuleForProductIdAndLocationId'
  end

  namespace :api do
  get 'price_rules_services/getAllPriceRulesForCategoriesAndAttributes'
  end

  namespace :api do
  get 'price_rules_services/getAllPriceRulesForLocationsAndAttributes'
  end

  namespace :api do
  get 'price_grids_services/addPriceGrid'
  end

  namespace :api do
  get 'price_grids_services/updatePriceGrid'
  end

  namespace :api do
  get 'price_grids_services/removePriceGrid'
  end

  namespace :api do
  get 'price_grids_services/getPriceGridByCategories'
  end

  namespace :api do
  get 'price_grids_services/getPriceGridByLocation'
  end

  namespace :api do
  get 'price_grids_services/getPriceGridByCategoryAndLocation'
  end

  namespace :api do
  get 'price_grids_services/getPriceGridByProductIdAndLocationId'
  end

  resources :price_grids

  resources :price_rules

  resources :product_attributes

  resources :custom_attributes
  
  get 'custom_attributes/index'
  post 'custom_attributes/add'
  get 'custom_attributes/new'
  
  namespace :api do
  get 'product_services/getAllDepartments'
  end

  namespace :api do
  get 'product_services/getCategoriesByDepartment'
  end

  namespace :api do
  get 'product_services/getSubCategoriesForCategory'
  end

  namespace :api do
  get 'product_services/getSegmentsForSubCategory'
  end

  namespace :api do
  get 'product_services/getProductsByDepartment'
  end

  namespace :api do
  post 'product_services/getProductsByCategory'
  end

  namespace :api do
  get 'product_services/getProductsBySubCategory'
  end

  namespace :api do
  get 'product_services/getProductsBySegment'
  end
  
  namespace :api do
  get 'product_services/getProductsByCustomAttributes'
 
  end
  
  namespace :api do
  get 'product_services/getAllattributes'
  end

  namespace :api do
  get 'ad_in_services_controller/getDepartments'
  
  get '/getDepartments' => 'ad_in_services_controller#getDepartments' 
  
  get 'ad_in_services_controller/getCategoriesByDepartment'
  end

  


 resources :event_managements
  
end
end

app/models/product_attribute.rb
class ProductAttribute < ActiveRecord::Base

end

app/controllers/product_attributes_controller.rb
class ProductAttributesController < ApplicationController
  before_action :set_product_attribute, only: [:show, :edit, :update, :destroy]

  # GET /product_attributes
  # GET /product_attributes.json
  def index
    @product_attributes = ProductAttribute.all
  end

  # GET /product_attributes/1
  # GET /product_attributes/1.json
  def show
  end

  # GET /product_attributes/new
  def new
    @product_attribute = ProductAttribute.new
  end

  # GET /product_attributes/1/edit
  def edit
  end

  # POST /product_attributes
  # POST /product_attributes.json
  def create
    @product_attribute = ProductAttribute.new(product_attribute_params)

    respond_to do |format|
      if @product_attribute.save
        format.html { redirect_to @product_attribute, notice: 'Product attribute was successfully created.' }
        format.json { render :show, status: :created, location: @product_attribute }
      else
        format.html { render :new }
        format.json { render json: @product_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_attributes/1
  # PATCH/PUT /product_attributes/1.json
  def update
    respond_to do |format|
      if @product_attribute.update(product_attribute_params)
        format.html { redirect_to @product_attribute, notice: 'Product attribute was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_attribute }
      else
        format.html { render :edit }
        format.json { render json: @product_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_attributes/1
  # DELETE /product_attributes/1.json
  def destroy
    @product_attribute.destroy
    respond_to do |format|
      format.html { redirect_to product_attributes_url, notice: 'Product attribute was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_attribute
      @product_attribute = ProductAttribute.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_attribute_params
      params.require(:product_attribute).permit(:product_id, :custom_attr_id, :value)
    end
end

app/helpers/product_attributes_helper.rb
module ProductAttributesHelper
end

app/views/product_attributes/_form.html.erb
<%= form_for(@product_attribute) do |f| %>
  <% if @product_attribute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_attribute.errors.count, "error") %> prohibited this product_attribute from being saved:</h2>

      <ul>
      <% @product_attribute.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :custom_attr_id %><br>
    <%= f.text_field :custom_attr_id %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_attributes/edit.html.erb
<h1>Editing product_attribute</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_attribute %> |
<%= link_to 'Back', product_attributes_path %>

app/views/product_attributes/index.html.erb
<h1>Listing product_attributes</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Custom attr</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_attributes.each do |product_attribute| %>
      <tr>
        <td><%= product_attribute.product_id %></td>
        <td><%= product_attribute.custom_attr_id %></td>
        <td><%= product_attribute.value %></td>
        <td><%= link_to 'Show', product_attribute %></td>
        <td><%= link_to 'Edit', edit_product_attribute_path(product_attribute) %></td>
        <td><%= link_to 'Destroy', product_attribute, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product attribute', new_product_attribute_path %>

app/views/product_attributes/new.html.erb
<h1>New product_attribute</h1>

<%= render 'form' %>

<%= link_to 'Back', product_attributes_path %>

app/views/product_attributes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @product_attribute.product_id %>
</p>

<p>
  <strong>Custom attr:</strong>
  <%= @product_attribute.custom_attr_id %>
</p>

<p>
  <strong>Value:</strong>
  <%= @product_attribute.value %>
</p>

<%= link_to 'Edit', edit_product_attribute_path(@product_attribute) %> |
<%= link_to 'Back', product_attributes_path %>